/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import SceneScale from "./script/Common/SceneScale"
import CenterPos from "./script/Common/CenterPos"
import Wall from "./script/GameScene/Wall"
import GameOver from "./script/GameScene/GameOver"
import GameScene from "./script/GameScene/GameScene"
import GameControl from "./script/GameControl"
import Bullet from "./script/GameScene/Bullet"
import Food from "./script/GameScene/Food"
import Snake from "./script/GameScene/Snake"
import SnakeBody from "./script/GameScene/SnakeBody"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("script/Common/SceneScale.js",SceneScale);
		reg("script/Common/CenterPos.js",CenterPos);
		reg("script/GameScene/Wall.js",Wall);
		reg("script/GameScene/GameOver.js",GameOver);
		reg("script/GameScene/GameScene.js",GameScene);
		reg("script/GameControl.js",GameControl);
		reg("script/GameScene/Bullet.js",Bullet);
		reg("script/GameScene/Food.js",Food);
		reg("script/GameScene/Snake.js",Snake);
		reg("script/GameScene/SnakeBody.js",SnakeBody);
    }
}
GameConfig.width = 960;
GameConfig.height = 540;
GameConfig.scaleMode ="fixedheight";
GameConfig.screenMode = "horizontal";
GameConfig.alignV = "middle";
GameConfig.alignH = "center";
GameConfig.startScene = "gameScene.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = true;
GameConfig.exportSceneToJson = true;

GameConfig.init();
